####Login Route
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"idur@yahoo.co.in"
}

####Register Route
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email":"rajib317@gmail.com"
}


####Refresh Token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc5MzI2MjUsImV4cCI6MTczOTQ5MDIyNSwiYXVkIjoiMiIsImlzcyI6ImxvY2FsaG9zdCJ9.jteYS7IY8LOCT8MdG_N6reP1aKX1mIUTisB2qSqOfqU"
}

####Verify Pin Route
POST http://localhost:3000/auth/verify-pin
Content-Type: application/json

{
    "email": "idur@yahoo.co.in",
    "pin": "436315"
}
####Set Password
POST http://localhost:3000/auth/set-password
Content-Type: application/json

{
    "email": "idur@yahoo.co.in",
    "password": "12345678"
}

####Testing a protected Route
GET http://localhost:3000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDc5MzI1NTMsImV4cCI6MTcwNzkzMzE1MywiYXVkIjoiMiIsImlzcyI6ImxvY2FsaG9zdCJ9.AtEmMOLVEqQEeUIfhvTktfZ_hcejhUDVtV-xrovJhUU